namespace EProcure.Web.Domain;

/// <summary>
/// Metadata about one PDF uploaded with a submission. The file bytes are NOT in the database;
/// they live wherever IFileStorage puts them (local folder now, blob storage later), and
/// <see cref="StorageKey"/> is how we find them again.
///
/// POPIA: the PDFs can contain personal information (IDs of directors, etc.). Access follows
/// the parent Submission exactly.
/// </summary>
public class UploadedDocument
{
    public int Id { get; set; }

    public int SubmissionId { get; set; }
    public Submission Submission { get; set; } = null!;

    /// <summary>Which checklist item this satisfies. NULL = supporting document not on the checklist.</summary>
    public int? TenderRequirementId { get; set; }
    public TenderRequirement? TenderRequirement { get; set; }

    /// <summary>Name as uploaded; shown to users only, NEVER used as a path on disk.</summary>
    public string OriginalFileName { get; set; } = string.Empty;

    /// <summary>Opaque key generated by the server (e.g. a GUID) and handed to IFileStorage.</summary>
    public string StorageKey { get; set; } = string.Empty;

    public string ContentType { get; set; } = "application/pdf";
    public long SizeBytes { get; set; }

    /// <summary>SHA-256 of the file: proves later that the document was not altered.</summary>
    public string Sha256 { get; set; } = string.Empty;

    public string UploadedByUserId { get; set; } = string.Empty;
    public ApplicationUser UploadedByUser { get; set; } = null!;

    public DateTime UploadedAtUtc { get; set; }
}
